CREATE DATABASE STUDENT_EXAMINATION_SYS;

CREATE TABLE STUDENT_EXAMINATION_SYS.STUDENT(
	ID VARCHAR(3) NOT NULL,
	NAME VARCHAR(20) NULL,
	AGE NUMBER(3) NULL,
	SEX VARCHAR(6) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE STUDENT_EXAMINATION_SYS.SUBJECT
(
	ID VARCHAR(4) NOT NULL, 
	SUBJECT VARCHAR(20) NULL,
	TEACHER VARCHAR(20) NULL,
    DESCRIPTION VARCHAR(50) NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE STUDENT_EXAMINATION_SYS.SCORE
(
	ID VARCHAR(1) NOT NULL, 
	STUDENT_ID VARCHAR(3) NULL,
	SUBJECT_ID VARCHAR(4) NULL,
    SCORE FLOAT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(ID)
);

INSERT INTO STUDENT ( ID, NAME, AGE, SEX ) VALUES ( '001', 'zhangsan', 18, 'male');
INSERT INTO STUDENT ( ID, NAME, AGE, SEX ) VALUES ( '002', 'lisi', 20, 'female');

INSERT INTO SUBJECT ( ID, SUBJECT, TEACHER, DESCRIPTION ) VALUES ( '1001', 'Chinese', 'Mr. Wang', 'the exam is easy');
INSERT INTO SUBJECT ( ID, SUBJECT, TEACHER, DESCRIPTION ) VALUES ( '1002', 'math', 'Miss Liu', 'the exam is difficult');

INSERT INTO SCORE ( ID, STUDENT_ID, SUBJECT_ID, SCORE ) VALUES ( '1', '001', '1001', 80);
INSERT INTO SCORE ( ID, STUDENT_ID, SUBJECT_ID, SCORE ) VALUES ( '2', '002', '1002', 60);
INSERT INTO SCORE ( ID, STUDENT_ID, SUBJECT_ID, SCORE ) VALUES ( '3', '001', '1001', 70);
INSERT INTO SCORE ( ID, STUDENT_ID, SUBJECT_ID, SCORE ) VALUES ( '4', '002', '1002', 60.5);
